version: "3.7"

services:
  lnvisweb:
    image: maxkotlan/ln-visualizer-web:v0.0.19@sha256:a478b12b62349b2a666b1fd2b297f4210de95d4306c737a076c69fee059dc479
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_LNVISUALIZER_WEB_PORT}:80"
    environment:
      LN_VISUALIZER_API_URL: "http://lnvisapi:5647"
    networks:
      default:
        ipv4_address: "${APP_LNVISUALIZER_WEB_IP}"
  lnvisapi:
    image: maxkotlan/ln-visualizer-api:v0.0.19@sha256:be92205988024b27897ad8218907219dc9e08a0239776aa35b5af936f1340983
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_LNVISUALIZER_API_PORT}:5647"
    volumes:
      - "${LND_DATA_DIR}:/lnd:ro"
    environment:
      LND_CERT_FILE: "/lnd/tls.cert"
      LND_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/readonly.macaroon"
      LND_SOCKET: "${LND_IP}:${LND_GRPC_PORT}"
    networks:
      default:
        ipv4_address: "${APP_LNVISUALIZER_API_IP}"
